dcConsData = [
    { name: "트리키/위자드.png", keywords: ["위자드", "위자드1"], tags: ["트리키"] },
    { name: "트리키/위자드2.png", keywords: ["위자드2"], tags: ["트리키"] },
    { name: "트리키/위자드3.png", keywords: ["위자드3"], tags: ["트리키"] },
    { name: "트리키/위자드4.png", keywords: ["위자드4"], tags: ["트리키"] },
    { name: "트리키/트리키.png", keywords: ["트리키"], tags: ["트리키"] },
    { name: "트리키/파킨.gif", keywords: ["파킨", "파킨1", "단영개"], tags: ["트리키"] },
    { name: "트리키/삽.png", keywords: ["삽", "그삽"], tags: ["트리키"] },
    { name: "트리키/유령.png", keywords: ["유령", "그유령"], tags: ["트리키"] },
    { name: "트리키/우승.png", keywords: ["우승"], tags: ["트리키"] },

    { name: "뿌테/빠요엔1.png", keywords: ["빠요엔", "빠요엔1"], tags: ["뿌테"] },
    { name: "뿌테/빠요엔2.gif", keywords: ["빠요엔2"], tags: ["뿌테"] },
    { name: "뿌테/빠요엔3.gif", keywords: ["빠요엔3"], tags: ["뿌테"] },

    { name: "나루토/어그로.gif", keywords: ["어그로", "미안하다", "싸움수준"], tags: ["나루토"] },
    { name: "나루토/카카시.gif", keywords: ["카카시", "카피닌자"], tags: ["나루토"] },

    { name: "제프벤브/벤브꼬우면.gif", keywords: ["꼬우면"], tags: ["제프벤브"] },
    { name: "제프벤브/벤브버그.gif", keywords: ["버그"], tags: ["제프벤브"] },
    { name: "제프벤브/벤브의도.gif", keywords: ["의도", "의도된"], tags: ["제프벤브"] },
    { name: "제프벤브/벤브직관.gif", keywords: ["직관", "직관적"], tags: ["제프벤브"] },
    { name: "제프벤브/제프짜잔.gif", keywords: ["짜잔"], tags: ["제프벤브"] },
    { name: "제프벤브/제프잔짜잔.gif", keywords: ["잔짜잔"], tags: ["제프벤브"] },

    { name: "주토피아/호랑이1.gif", keywords: ["호랑이", "호랑이1"], tags: ["주토피아"] },
    { name: "주토피아/호랑이2.gif", keywords: ["호랑이2"], tags: ["주토피아"] },
    { name: "주토피아/호랑이3.gif", keywords: ["호랑이3"], tags: ["주토피아"] },
    { name: "주토피아/호랑이4.gif", keywords: ["호랑이4"], tags: ["주토피아"] },

    { name: "선생님/갓겜.png", keywords: ["갓겜"], tags: ["선생님"] },
    { name: "선생님/개돼지.png", keywords: ["개돼지"], tags: ["선생님"] },
    { name: "선생님/계산중.png", keywords: ["계산중"], tags: ["선생님"] },
    { name: "선생님/그빌드.png", keywords: ["그빌드"], tags: ["선생님"] },
    { name: "선생님/망빌드.png", keywords: ["망빌드"], tags: ["선생님"] },
    { name: "선생님/망테크.png", keywords: ["망테크"], tags: ["선생님"] },
    { name: "선생님/벌써밤.png", keywords: ["벌써밤"], tags: ["선생님"] },
    { name: "선생님/훌륭.png", keywords: ["훌륭"], tags: ["선생님"] },
    { name: "선생님/힘의차이.png", keywords: ["힘의차이"], tags: ["선생님"] },

    { name: "흠/흠.png", keywords: ["흠"], tags: ["흠"] },
    { name: "흠/흠고퀄.png", keywords: ["흠고퀄", "고퀄흠"], tags: ["흠"] },
    { name: "흠/흠란.gif", keywords: ["흠란"], tags: ["흠"] },
    { name: "흠/흠발퀄.png", keywords: ["흠발퀄", "발퀄흠"], tags: ["흠"] },
    { name: "흠/흠스웩.png", keywords: ["흠스웩", "스웩흠"], tags: ["흠"] },
    { name: "흠/흠왜곡.gif", keywords: ["흠왜곡", "왜곡흠"], tags: ["흠"] },
    { name: "흠/흠회전1.gif", keywords: ["흠회전", "회전흠", "흠회전1", "회전흠1"], tags: ["흠"] },
    { name: "흠/흠회전2.gif", keywords: ["흠회전2", "회전흠2"], tags: ["흠"] },
    { name: "흠/흠회전3.gif", keywords: ["흠회전3", "회전흠3"], tags: ["흠"] },
    { name: "흠/흠흠흠.png", keywords: ["흠흠흠"], tags: ["흠"] },

    { name: "볼트/볼트공중.png", keywords: ["볼트공중"], tags: ["볼트보이"] },
    { name: "볼트/볼트구토.png", keywords: ["볼트구토"], tags: ["볼트보이"] },
    { name: "볼트/볼트나무.png", keywords: ["볼트나무"], tags: ["볼트보이"] },
    { name: "볼트/볼트넷여친.png", keywords: ["볼트넷여친"], tags: ["볼트보이"] },
    { name: "볼트/볼트넷친구.png", keywords: ["볼트넷친구"], tags: ["볼트보이"] },
    { name: "볼트/볼트닌자.png", keywords: ["볼트닌자", "볼트대게"], tags: ["볼트보이"] },
    { name: "볼트/볼트딸딸.png", keywords: ["볼트딸딸"], tags: ["볼트보이"] },
    { name: "볼트/볼트심리.png", keywords: ["볼트심리"], tags: ["볼트보이"] },
    { name: "볼트/볼트침대.png", keywords: ["볼트침대"], tags: ["볼트보이"] },
    { name: "볼트/볼트투시.png", keywords: ["볼트투시"], tags: ["볼트보이"] },
    { name: "볼트/볼트펄럭.png", keywords: ["볼트펄럭"], tags: ["볼트보이", "펄럭"] },
    { name: "볼트/볼트활활.png", keywords: ["볼트활활"], tags: ["볼트보이"] },

    { name: "풍당당/이풍당당1.gif", keywords: ["이풍당당1", "이풍당당"], tags: ["풍당당"] },
    { name: "풍당당/이풍당당2.gif", keywords: ["이풍당당2"], tags: ["풍당당"] },
    { name: "풍당당/이풍당당3.gif", keywords: ["이풍당당3"], tags: ["풍당당"] },
    { name: "풍당당/문풍당당1.gif", keywords: ["문풍당당1", "문풍당당"], tags: ["풍당당"] },
    { name: "풍당당/문풍당당2.gif", keywords: ["문풍당당2"], tags: ["풍당당"] },
    { name: "풍당당/문풍당당3.gif", keywords: ["문풍당당3"], tags: ["풍당당"] },
    { name: "풍당당/예풍당당.gif", keywords: ["예풍당당"], tags: ["풍당당"] },
    { name: "풍당당/비풍당당.gif", keywords: ["B풍당당", "비풍당당", "벤풍당당"], tags: ["풍당당", "제프벤브"] },

    { name: "불편/불편.png", keywords: ["불편"], tags: ["불편"] },
    { name: "불편/편안.png", keywords: ["편안"], tags: ["불편"] },
    { name: "불편/불편불.gif", keywords: ["불편불"], tags: ["불편"] },
    { name: "불편/불편해짐.gif", keywords: ["불편해짐"], tags: ["불편"] },

    { name: "우리핵/우리핵드럼.gif", keywords: ["우리핵드럼"], tags: ["우리핵"] },
    { name: "우리핵/우리핵박수1.gif", keywords: ["우리핵박수1", "우리핵박수"], tags: ["우리핵"] },
    { name: "우리핵/우리핵박수2.gif", keywords: ["우리핵박수2"], tags: ["우리핵"] },
    { name: "우리핵/우리핵박수3.gif", keywords: ["우리핵박수3"], tags: ["우리핵"] },
    { name: "우리핵/우리핵빵야.gif", keywords: ["우리핵빵야"], tags: ["우리핵"] },
    { name: "우리핵/우리핵쌍안경.gif", keywords: ["우리핵쌍안경"], tags: ["우리핵"] },
    { name: "우리핵/우리핵아닌데.gif", keywords: ["우리핵아닌데"], tags: ["우리핵"] },
    { name: "우리핵/우리핵안녕.gif", keywords: ["우리핵안녕"], tags: ["우리핵"] },
    { name: "우리핵/우리핵투정.gif", keywords: ["우리핵투정"], tags: ["우리핵"] },

    { name: "좋은말/좋은말네말맞.gif", keywords: ["네말맞"], tags: ["좋은말"] },
    { name: "좋은말/좋은말멋있다.gif", keywords: ["멋있다"], tags: ["좋은말"] },
    { name: "좋은말/좋은말좋겠다.gif", keywords: ["좋겠다"], tags: ["좋은말"] },
    { name: "좋은말/좋은말짱이야.gif", keywords: ["짱이야"], tags: ["좋은말"] },
    { name: "좋은말/좋은말축하해.gif", keywords: ["축하해"], tags: ["좋은말"] },

    { name: "롤코/수직낙하.png", keywords: ["수직낙하"], tags: ["롤코"] },
    { name: "롤코/촉수.png", keywords: ["촉수"], tags: ["롤코"] },
    { name: "롤코/화장실.png", keywords: ["화장실"], tags: ["롤코"] },

    { name: "핫산/핫산발상.png", keywords: ["핫산발상"], tags: ["핫산"] },
    { name: "핫산/핫산쾅.png", keywords: ["핫산쾅", "쾅"], tags: ["핫산"] },
    { name: "핫산/핫산펑.png", keywords: ["핫산펑", "펑"], tags: ["핫산"] },

    { name: "펄럭/펄럭1.gif", keywords: ["펄럭1", "펄럭"], tags: ["펄럭"] },
    { name: "펄럭/펄럭2.gif", keywords: ["펄럭2"], tags: ["펄럭"] },

    { name: "야인시대/4딸라.png", keywords: ["4딸라", "사딸라"], tags: ["야인시대"] },
    { name: "야인시대/오케이.png", keywords: ["오케이"], tags: ["야인시대"] },

    { name: "캐피탈/노예일해.png", keywords: ["노예일해"], tags: ["캐피탈"] },
    { name: "캐피탈/이지붐.jpg", keywords: ["이지붐"], tags: ["캐피탈"] },
    { name: "캐피탈/퍄산.png", keywords: ["파산", "퍄산"], tags: ["캐피탈"] },
    { name: "캐피탈/폴짝.png", keywords: ["폴짝"], tags: ["캐피탈"] },

    { name: "겐고로/아아.png", keywords: ["아아"], tags: ["겐고로"] },
    { name: "겐고로/마치.png", keywords: ["마치"], tags: ["겐고로"] },

    { name: "얼음꿀차/매우정상.png", keywords: ["매우정상"], tags: ["얼음꿀차"] },
    { name: "얼음꿀차/상담필요.png", keywords: ["상담필요"], tags: ["얼음꿀차"] },

    { name: "집요정/쑥스럽.png", keywords: ["쑥스럽", "집요정쑥스럽"], tags: ["집요정"] },
    { name: "집요정/모름.png", keywords: ["모름", "모릅니다", "집요정모름", "집요정모릅니다"], tags: ["집요정"] },
    { name: "집요정/인증.png", keywords: ["인증", "인증함", "집요정인증", "집요정인증함"], tags: ["집요정"] },
    { name: "집요정/선물.png", keywords: ["선물", "선물이야", "집요정선물", "집요정선물이야"], tags: ["집요정"] },
    { name: "집요정/워워.png", keywords: ["워워", "집요정워워"], tags: ["집요정"] },
    { name: "집요정/아이구야.png", keywords: ["아이구야", "집요정아이구야"], tags: ["집요정"] },
    { name: "집요정/어흑.png", keywords: ["어흑", "어흑흑", "집요정어흑", "집요정어흑흑"], tags: ["집요정"] },
    { name: "집요정/O.png", keywords: ["O", "o", "집요정O", "집요정o"], tags: ["집요정"] },
    { name: "집요정/X.png", keywords: ["X", "x", "집요정X", "집요정x"], tags: ["집요정"] },
    { name: "집요정/돼.png", keywords: ["돼", "집요정돼"], tags: ["집요정"] },
    { name: "집요정/안돼.png", keywords: ["안돼", "집요정안돼"], tags: ["집요정"] },
    { name: "집요정/눈물.png", keywords: ["눈물", "집요정눈물"], tags: ["집요정"] },
    { name: "집요정/사망.png", keywords: ["사망", "집요정사망"], tags: ["집요정"] },
    { name: "집요정/당황끄덕.png", keywords: ["당황끄덕", "끄덕", "집요정당황끄덕", "집요정끄덕"], tags: ["집요정"] },
    { name: "집요정/두근두근.png", keywords: ["두근두근", "집요정두근두근"], tags: ["집요정"] },
    { name: "집요정/항복.png", keywords: ["항복", "집요정항복"], tags: ["집요정"] },
    { name: "집요정/하트.png", keywords: ["하트", "집요정하트"], tags: ["집요정"] },
    { name: "집요정/무시무시.png", keywords: ["무시무시", "집요정무시무시"], tags: ["집요정"] },
    { name: "집요정/아니다.png", keywords: ["아니다", "집요정아니다"], tags: ["집요정"] },
    { name: "집요정/팩트.png", keywords: ["팩트", "집요정팩트"], tags: ["집요정"] },
    { name: "집요정/고양이가.png", keywords: ["고양이가", "집요정고양이가"], tags: ["집요정"] },
    { name: "집요정/두근.png", keywords: ["두근", "집요정두근"], tags: ["집요정"] },
    { name: "집요정/죽창.png", keywords: ["죽창", "집요정죽창"], tags: ["집요정"] },
    { name: "집요정/인정.png", keywords: ["인정", "집요정인정"], tags: ["집요정"] },
    { name: "집요정/물음표.png", keywords: ["물음표", "?", "집요정물음표"], tags: ["집요정"] },
    { name: "집요정/우웩.png", keywords: ["우웩", "집요정우웩"], tags: ["집요정"] },
    { name: "집요정/어그래.png", keywords: ["어그래", "집요정어그래"], tags: ["집요정"] },
    { name: "집요정/조의.png", keywords: ["조의", "집요정조의"], tags: ["집요정"] },
    { name: "집요정/안녕.png", keywords: ["안녕", "집요정안녕"], tags: ["집요정"] },
    { name: "집요정/잘자.png", keywords: ["잘자", "집요정잘자"], tags: ["집요정"] },
    { name: "집요정/수근수근.png", keywords: ["수근수근", "집요정수근수근"], tags: ["집요정"] },
    { name: "집요정/조와.png", keywords: ["조와", "집요정조와"], tags: ["집요정"] },

    { name: "기타/역가서순.png", keywords: ["서순"], tags: ["기타"] },
    { name: "기타/역가순서.png", keywords: ["순서"], tags: ["기타"] },
    { name: "기타/눈물앵무.gif", keywords: ["눈물앵무"], tags: ["기타"] },
    { name: "기타/혼란앵무.gif", keywords: ["혼란앵무"], tags: ["기타"] },
    { name: "기타/AMD.png", keywords: ["AMD"], tags: ["기타"] },
    { name: "기타/마참내.png", keywords: ["마참내"], tags: ["기타"] },
    { name: "기타/시간절약.png", keywords: ["시간절약"], tags: ["기타"] },
    { name: "기타/즐겁다.png", keywords: ["즐겁다"], tags: ["기타"] },
    { name: "기타/손도깔끔.png", keywords: ["손도깔끔"], tags: ["기타"] },
    { name: "기타/제리감사.gif", keywords: ["제리감사"], tags: ["기타"] },
    { name: "기타/톰감사.gif", keywords: ["톰감사"], tags: ["기타"] },
    { name: "기타/민트초코.gif", keywords: ["민트초코"], tags: ["기타"] }
];

var originalAddChatMessage = addChatMessage;
addChatMessage = function(nick, message, data) {
  var chat = originalAddChatMessage(nick, message, data);
  chat.style.top = Math.random() * 100 + '%';
  if (data.color && configData.personalColor) {
    chat.lower.msg.style.color = data.color;
  }
  return chat;
}